spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: ALWAYS
      table-prefix: BATCH_ #BATCH_ = default




